-- Create waitlist_entries table
CREATE TABLE IF NOT EXISTS waitlist_entries (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       TEXT        UNIQUE NOT NULL,
  name        TEXT,
  role        TEXT,
  note        TEXT        CHECK (char_length(note) <= 500),
  source      TEXT,
  metadata    JSONB,
  created_at  TIMESTAMPTZ DEFAULT now()
);

-- Index for fast duplicate-check lookups
CREATE UNIQUE INDEX IF NOT EXISTS waitlist_entries_email_idx
  ON waitlist_entries (email);
